#!/usr/bin/env python3
"""Check the checked-in public API manifest for drift."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
ENTRYPOINT = ROOT / "Harness.qi"
MANIFEST = ROOT / "public-api.txt"


def strip_comments(source: str) -> str:
    return re.sub(r"//[^\n]*", "", source)


def normalize(declaration: str) -> str:
    return re.sub(r"\s+", " ", declaration).strip()


def matching_brace(source: str, opening: int) -> int:
    depth = 0
    for index in range(opening, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("unclosed public type declaration")


def declarations(path: Path) -> list[str]:
    source = strip_comments(path.read_text(encoding="utf-8"))
    found: list[str] = []

    for match in re.finditer(r"公开\s+类型\s+[^\s{]+\s*\{", source):
        opening = source.find("{", match.start())
        closing = matching_brace(source, opening)
        found.append(normalize(source[match.start() + 3 : closing + 1]))

    for match in re.finditer(r"公开\s+函数\s+", source):
        opening = source.find("{", match.end())
        if opening < 0:
            raise ValueError(f"public function without body in {path.name}")
        found.append(normalize(source[match.start() + 3 : opening]))

    return sorted(found)


def render_manifest(root: Path = ROOT) -> str:
    entrypoint = root / "Harness.qi"
    modules = {
        path.stem: declarations(path)
        for path in sorted(root.glob("*.qi"), key=lambda item: item.name)
        if path != entrypoint
        and re.search(r"^包\s+Harness(?:\.[^\s;]+)?\s*;", path.read_text(encoding="utf-8"), re.MULTILINE)
    }
    entry_source = strip_comments(entrypoint.read_text(encoding="utf-8"))
    reexports = re.findall(r"公开\s+导入\s+([^;\s]+)\s*;", entry_source)

    missing = sorted(set(reexports) - modules.keys())
    if missing:
        raise ValueError("top-level re-export has no direct module: " + ", ".join(missing))

    lines = [
        "# qi-harness public API baseline",
        "# Generated by: ./check-public-api.py --update",
        "# Review manifest changes as release-facing API changes.",
        "",
        "[Harness]",
    ]
    lines.extend(sorted(declaration for module in reexports for declaration in modules[module]))

    for module, module_declarations in modules.items():
        lines.extend(("", f"[Harness.{module}]"))
        lines.extend(module_declarations)

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update", action="store_true", help="replace the checked baseline")
    args = parser.parse_args()

    try:
        generated = render_manifest()
    except (OSError, ValueError) as error:
        print(f"error: cannot generate public API manifest: {error}", file=sys.stderr)
        return 1

    if args.update:
        MANIFEST.write_text(generated, encoding="utf-8")
        print(f"updated {MANIFEST.relative_to(ROOT)}")
        return 0

    if not MANIFEST.exists():
        print("error: public-api.txt is missing; run ./check-public-api.py --update", file=sys.stderr)
        return 1

    expected = MANIFEST.read_text(encoding="utf-8")
    if expected == generated:
        print("public API manifest matches source")
        return 0

    diff = difflib.unified_diff(
        expected.splitlines(), generated.splitlines(),
        fromfile="public-api.txt", tofile="generated public API", lineterm="",
    )
    print("\n".join(diff), file=sys.stderr)
    print(
        "error: public API drift detected; preserve compatibility or intentionally run "
        "./check-public-api.py --update and document the migration",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
